name: students_reminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2

  # State management
  flutter_riverpod: ^2.5.1
  rxdart: ^0.28.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1

  # Local storage
  shared_preferences: ^2.5.3

  # Location + Maps
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Media
  image_picker: ^1.2.0

  # Utils
  intl: ^0.19.0
  http: ^1.2.2   # ✅ Needed for Google Maps API calls
  flutter_typeahead: ^5.2.0  # ✅ Keep this for search bar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png