// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-gGMWiYm9MnK6j8ncyzYfm7rcOmnyQXQ',
    appId: '1:974832763756:web:5ed1e012d3ab6b74d1a949',
    messagingSenderId: '974832763756',
    projectId: 'generic-app-169ba',
    authDomain: 'generic-app-169ba.firebaseapp.com',
    storageBucket: 'generic-app-169ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaaUKBxtSVOKsGGXCiNSw4c5OAi8YS-I',
    appId: '1:974832763756:android:fbe095c579c0e566d1a949',
    messagingSenderId: '974832763756',
    projectId: 'generic-app-169ba',
    storageBucket: 'generic-app-169ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2J8dKzqUgdphag7zIgQgqMRN3jdXnU4c',
    appId: '1:974832763756:ios:997a7752043b4882d1a949',
    messagingSenderId: '974832763756',
    projectId: 'generic-app-169ba',
    storageBucket: 'generic-app-169ba.firebasestorage.app',
    iosBundleId: 'com.example.studentsReminder',
  );
}
