// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZRL1b5J13RLzuh9czT35EGZ_JpNClMU',
    appId: '1:727140327360:web:09cffeb179aa1fd9813225',
    messagingSenderId: '727140327360',
    projectId: 'studentreminderg2',
    authDomain: 'studentreminderg2.firebaseapp.com',
    storageBucket: 'studentreminderg2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNHswmkaolAuTf-KqUqvpIX8vk1vVoj5U',
    appId: '1:727140327360:android:090c8d1622fd864a813225',
    messagingSenderId: '727140327360',
    projectId: 'studentreminderg2',
    storageBucket: 'studentreminderg2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu51EFazzNjQ_cxptay9DNy-JcWiVwXZA',
    appId: '1:727140327360:ios:e58282be27fe1729813225',
    messagingSenderId: '727140327360',
    projectId: 'studentreminderg2',
    storageBucket: 'studentreminderg2.firebasestorage.app',
    iosBundleId: 'com.example.studentsReminder',
  );

}